name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://54.167.164.84:8080"
        user: "admin"
        token: ${{ secrets.TOKEN }}
        job: "GitHubTrigger"
