name: Trigger Jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://52.91.82.181:8080"
        user: ${{ secrets.LAB_USERNAME }}
        token: ${{ secrets.TOKEN }}
        job: "GitHubTrigger"
